[project]
name = "dump-heap"
version = "0.1.0"
description = "Dumps the heap of a running Python program."
readme = "README.md"
requires-python = ">=3.12"

[dependency-groups]
dev = [
    "mypy>=1.13.0",
]
